name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linudx/arm64

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_SKIP: pp*
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_ARCHS_LINUX: "auto aarch64"
          CIBW_ARCHS_WINDOWS: "auto"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  # Build the source distribution under Linux
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout submodule
        run: git submodule update --init slvs

      - uses: actions/setup-python@v2

      - name: Build source distribution
        run: |
          pip install twine
          python setup.py sdist
          # Check whether the source distribution will render correctly
          twine check dist/*.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.tar.gz
